### ISSUE TITLE
Decide on unit test framework

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#18]
Which unit test framework should we use for SOILWAT2 out of the many frameworks available (see [list](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C))?

Since we attempt that stand-along SOILWAT2 runs under multiple platforms, we need a test framework which allows testing across these platforms.

Should we use one of the small ones, e.g., 
- [CUnit](http://cunit.sourceforge.net/),
- [MinUnit](http://www.jera.com/techinfo/jtns/jtn002.html)

or one of the large frameworks: 
- [Check](https://libcheck.github.io/check/), 
- [Criterion](https://github.com/Snaipe/Criterion)?

What do our programmers think, @Zachary-Kramer @BrendenBe1 @ksodhi-uwyo?

**Comment by Zachary-Kramer** [comment]
I don't have time today to look over the ones you provided, but I will tomorrow. For now, a coworker has recommended [GoogleTest](https://github.com/google/googletest) to me. It targets C++ but works for C as well.

I feel that we don't do much development on SOILWAT2, and we don't have anyone in a permanent QA position, so I will learn towards whichever framework is the easiest to use and maintain.

**Comment by Zachary-Kramer** [comment]
I've now had time to look over the list you provided.

My top preference is Google Test, mostly because it was recommended to me by a principal software developer and it seems to be simple to use with good documentation. It also has a lot of functionality and assertions that may be useful, even if we don't immediately use them.

My second preference is Check, because it seems more developed than the smaller frameworks and is also simple to use.

Unity also seems to be gaining popularity, though I don't have many thoughts on it.

**Comment by dschlaep** [comment]
I agree [GoogleTest](https://github.com/google/googletest) looks good. Let's go with it! Thank you for your evaluation of the options!
