### ISSUE TITLE
Reduce/eliminate the R specific onGet_*/onSet_* functions

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/SOILWAT2#32]
Is it possible to reduce/eliminate duplicate functionality?

**Comment by Zachary-Kramer** [comment]
I can't think much about this at the moment, but I believe that they should be kept separate. 

Although on the surface it looks like they could be combined or share some code, I think their functionality is quite different. onGet is used to return an object of the class to R, which can then be further modified in R before being sent back to SOILWAT2 via the onSet function. So onGet needs to assign values to the object, onSet needs to assign values to C variables, and these function calls need to happen at different times. With that in mind, I don't see much shared functionality. It wouldn't really be possible to even combine the object functionality (e.g. PROTECT, GET_SLOT, etc.) because one is setting slots and the other is grabbing. 

Is there duplicate functionality that I'm not seeing?

**Comment by dschlaep** [comment]
Good points. 

However, why are we re-constructing all the c variables and structures, e.g., 'SW_SOILWAT', 'SW_WEATHER, as instances of the R API class 'SEXP'? Couldn't we instead use SOILWAT2's c variables and it's functions and pass these to package rSOILWAT2?

**Comment by Zachary-Kramer** [comment]
I don't fully understand what you mean. Are you investigating if we can get rid of R's classes entirely and use the C structures, which are essentially identical?

I'm likely misunderstanding your questions, but...

> Why are we re-constructing all the c variables and structures, e.g., 'SW_SOILWAT', 'SW_WEATHER, as instances of the R API class 'SEXP'? 

Currently, rSFSW2 needs access to the SEXP object in order to modify or read its values (now, that object could be of many things, but in this case its of an S4 class). The SEXP object is created in SOILWAT2, as opposed to instantiated in R, mostly because SOILWAT2 holds the functionality for reading the .in files.

> Couldn't we instead use SOILWAT2's c variables and it's functions and pass these to package rSOILWAT2?

C variables cannot directly be passed back to rSOILWAT2, so they would be returned as one of the R Internals' objects. If R wanted to modify a value, it would have to be passed back as one of these objects too, which is what we're doing with the classes, just all at once.

I'm not dismissing your concerns, just need some clarification. Sorry if you already knew this information, I can get into more detail once I fully understand the questions.

**Comment by dschlaep** [comment]
> Currently, rSFSW2 needs access to the SEXP object in order to modify or read its values (now, that object could be of many things, but in this case its of an S4 class)

The SEXP object is only a S4 class because we (the developer of the original version of Rsoilwat31) made that decision. We could decide otherwise if it is in our interest.

>C variables cannot directly be passed back to rSOILWAT2.

I don't believe that this is completely correct:
- C variables of some C base types (int*, double*, ...) can be passed to and fro R directly via the `.C` interface (see [Interface-functions-_002eC-and-_002eFortran](https://cran.r-project.org/doc/manuals/R-exts.html#Interface-functions-_002eC-and-_002eFortran)).
- the R package 'rSOILWAT2' consists both of C code and R code. We could move the rSOILWAT2 specific C code from the repository 'SOILWAT2' and place it instead in the repository 'rSOILWAT2' to be compiled into the shared object together with the 'core' SOILWAT2 C code imported as sub-module. In this scenario C variables would be passed directly to rSOILWAT2, i.e., its C functions. I believe such separation should make it easier for people working/maintaining SOILWAT2?

**Comment by dschlaep** [comment]
Move c code solely used by rSOILWAT2 from SOILWAT2 to rSOILWAT2, see https://github.com/Burke-Lauenroth-Lab/rSOILWAT2/issues/66

**Comment by dschlaep** [comment]
The code in the `SOILWAT2` repository contains 189 occurrences of `RSOILWAT` across 37 files.
