### ISSUE TITLE
Tree transpiration is not 0 in save_soilwat_output branch despite trees being turned off

### ISSUE THREAD

**Issue by kpalmqui** [Burke-Lauenroth-Lab/SOILWAT2#53]
Transpiration values are not zero when given functional groups are turned off in sbe_prod_v31.in. In addition, the transp_total within a given layer is not equal to the summed transpiration across all SOILWAT2 functional types for that soil layer.

**Comment by BrendenBe1** [comment]
Most recent commit should fix this bug. The problem was that the get_transp function was writing the values in the form of total_layer1...total_endlayer tree_layer1...tree_endlayer and the column headers were going total_layer1 tree_layer1... so the values were in the right location the headers were off. This has been fixed and now the transp_total value is equal to the sum of the other transp values as it should be and trees is not coming up with any values.

**Comment by kpalmqui** [comment]
I confirmed this problem has been fixed.
